import './globals.css'
import '../fontawesome-free-5.12.1-web'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Navbar, Footer, Sidebar } from '@/components/'
import { Providers } from './redux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Hotel App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head>
        <link rel='apple-touch-icon' href='%PUBLIC_URL%/logo192.png' />
        <base href='#' target='_blank' />
      </head>
      <body>
        <Navbar />
        <Providers>{children}</Providers>
        <Footer />
        <Sidebar />
      </body>
    </html>
  )
}
