import './globals.css'
import { Inter } from 'next/font/google'
import { Navbar, Footer, Sidebar } from '@/layout'
import { ReduxProvider } from '@/redux/provider'
import { Metadata } from 'next'
import FiltersCleaner from '@/shared/lib/FiltersCleaner'
import ClientOnly from '@/shared/lib/ClientOnly'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'E-Commerce | React App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head>
        <base href='#' target='_blank' />
      </head>
      <body className={inter.className}>
        <ClientOnly>
          <ReduxProvider>
            <FiltersCleaner />
            <Navbar />
            {children}
            <Footer />
            <Sidebar />
          </ReduxProvider>
        </ClientOnly>
      </body>
    </html>
  )
}
